antiwork/gumboard

app/api/boards/[id]/notes/route.ts
app/api/boards/all-notes/notes/route.ts
lib/constants.ts

Extracts duplicate color arrays into a shared constants file for better maintainability.
- Created `lib/constants.ts` with `NOTE_COLORS` array
- Updated API routes to use the shared constant
- Removed 26 lines of duplicate code
- **DRY principle**: Single source of truth for note colors
- **Easier maintenance**: Change colors in one place
- **Type safety**: Added `NoteColor` type for better TypeScript support
No functional changes - purely a refactoring.

refactor: extract NOTE_COLORS to shared constants

---

docker-compose.yml
env.example

This PR makes the PostgreSQL port configurable via an environment variable `POSTGRES_PORT`.
On many developer machines, port `5432` may already be in use. This change allows contributors to specify a custom port without modifying shared files.
- Updated `docker-compose.yml` to use `${POSTGRES_PORT:-5432}`
- Updated `.env.example` with `POSTGRES_PORT=5432`
Tested locally with `5434`, container is healthy and accessible.

Enhance: Make PostgreSQL port configurable using POSTGRES_PORT env variable

---

app/boards/[id]/page.tsx

fixes #188 
**Summary**
In this PR Updated the board page so that empty-state messages for “No notes found” and “No notes yet” are absolutely positioned within the board, keeping them visible without requiring the user to scroll. Added after and before video now.
Before
https://github.com/user-attachments/assets/c73a48a0-2ec4-42a0-a91f-60a4fd00d5dc
After
https://github.com/user-attachments/assets/7c7cd37e-e666-4705-9930-541c40d44be5

fix: make empty state visible without scrolling by overlaying it in board area

---

app/boards/[id]/page.tsx
components/note.tsx

Fixes: https://github.com/antiwork/gumboard/issues/178
Root Causes:
1. Flex-1 stretching: The Note component had flex-1 classes on containers (lines 463 and 483 in note.tsx), which caused the content to expand and fill all available vertical space
within the fixed-height container.
2. Overestimated height calculations: The calculateNoteHeight function in the board page was calculating too much height for checklist items:
- Header height was set to 76px (too high)
- Item height was 32px per checklist item (actual is ~28px)
- Item spacing was 8px (actual is 4px with space-y-1)
- Extra padding of 40px for the button

fix: whitespace bug

---

components/checklist-item.tsx
components/note.tsx
components/sticky-notes-demo.tsx
tests/e2e/home-page.spec.ts
tests/e2e/notes.spec.ts

Fixes #240
#184 broke the homepage and below is what I did to resolve it
- Added a `syncDB` prop to `Note` component. It defaults to `true` and when set to `false` will not synchronize it's state with database allowing local edits
- I added spec because things are moving fast and home page with bugs won't look good on the brand. I think this will help with mobility without breaking stuff
https://github.com/user-attachments/assets/7b17c1ce-487e-410c-a97f-3a4ee18dc512

fix: homepage sticky notes editing after #184

---

README.md

fixes #259 
`npm run db:push` fails when using `.env.local` file 
more context: https://github.com/prisma/prisma/issues/3865
when using `.env.local` file, prisma db push fails
when using `.env` file, prisma db push runs ok

chore: replace .env.local with .env file in README Getting Started section

---

prisma/migrations/20250812162423_add_archived_at_to_note/migration.sql

This migration introduces the `archivedAt` timestamp column to the `notes` table, setting its value for existing notes where `done` was true. The `done` column is subsequently dropped, completing the transition to the new field structure. This change aligns with previous updates to ensure consistency in the database schema.

feat(migration): add archivedAt column to notes and remove done column

---

components/note.tsx

This PR fixes checklist reordering not persisting after refresh. The UI now recalculates order for each item on drag-and-drop and sends the updated list to the notes update API, ensuring the new order is saved.
Before:
https://github.com/user-attachments/assets/24fb606c-5925-4f2b-9764-56c5e19490a4
After:
https://github.com/user-attachments/assets/19d243ab-9dbb-4963-8ca5-b95c8a66abc6

fix: persist checklist item order after drag-and-drop

---

components/note.tsx
tests/e2e/add-task-button.spec.ts
tests/e2e/archive.spec.ts

This PR fixes 6 tests in file tests/e2e/archive.spec.ts in PR https://github.com/antiwork/gumboard/pull/312
Before:
After:-

fix: archieve e2e tests

---

app/boards/[id]/page.tsx
app/not-found.tsx
app/public/boards/[id]/page.tsx
tests/e2e/board.spec.ts
tests/e2e/not-found.spec.ts

fixes #385 
add global not-found page and add links to go home to other not found pages + e2e tests
**before:**
**after:**
upd: link text was update to Go to Gumboard everywhere

feat: add global not-found page and add links to go home to other not found pages + e2e tests

---

app/api/boards/[id]/public/route.ts
app/api/boards/[id]/route.ts
prisma/migrations/20250814172001_add_user_org_index/migration.sql
prisma/schema.prisma

Board API routes were fetching entire organization member lists to check if a single user has access. These **O(n)** operations occur on every board interaction - viewing boards, creating/editing notes, updating settings - making them extremely frequent hot paths that degrade performance as organizations grow.
* `app/api/boards/[id]/route.ts:12` - **GET** loads all members, uses only one for membership check
* `app/api/boards/[id]/route.ts:78-89` - **PUT** loads all members, uses only one for admin check
* `app/api/boards/[id]/route.ts:163-179` - **DELETE** loads all members (including names/emails) unnecessarily
* `app/api/boards/[id]/public/route.ts:17-31` - **PUT** loads all members for single-user verification
* Replaced `include: { members: true }` with direct database queries using …

perf: Replace O(n) org membership checks with O(1) lookups + add index 

---

package-lock.json
package.json

Remove `recharts` package from dependencies as it is no longer used in the codebase.
Fixes https://github.com/antiwork/gumboard/issues/397

chore: remove unused recharts dependency

---

app/dashboard/page.tsx

Inin relation to #411 and fixes #424

Fix: board card size symmetry on dashboard page 

---

app/public/boards/[id]/page.tsx

#411 
currently the flow is
1. you are login (but not in the organization of the board that is shared and now turn private) => you try to access it => it redirect you to  login page. 
> problem
you are already login. it should only take us to auth/signup when the status return 401 (session not found)
https://github.com/user-attachments/assets/1f3a5e62-b98c-4323-af39-e5eac8c6d915
the expected flow:
1. you are login (but not in the organization of the board that is shared and now turn private) => you try to access it => it shows a appropriate message that the board is private
https://github.com/user-attachments/assets/8bbacd06-ef7f-463e-b532-9d9c26113b88

fix: work flow when person who is not in organization is accessing a private board

---

app/layout.tsx
components/theme-provider.tsx
components/ui/alert-dialog.tsx
components/ui/dialog.tsx
components/ui/label.tsx
components/ui/popover.tsx
components/ui/sonner.tsx
components/ui/tooltip.tsx

Removed `"use client"` directives from components and pages that do not require client-side rendering. This reduces the client bundle size, improves maintainability, and makes the server/client boundary clearer.
- Audited all files with `"use client"` in `app/` and `components/`
- Kept `"use client"` only where necessary:
- React hooks are used (`useState`, `useEffect`, etc.)
- Browser APIs are accessed (`window`, `document`, `localStorage`, etc.)
- Required by Next.js (e.g., error boundaries)
- Removed it from files safe to render as server components
- **Performance**: Smaller client-side JavaScript footprint
- **Clarity**: Clearer separation of server vs client components
- **Maintainability**: Easier to reason about rendering requirements
- Reduced number of client components
- Leaner …

refactor: remove unnecessary "use client" directives to reduce client bundle size

---

app/api/boards/[id]/route.ts
app/api/boards/route.ts
tests/e2e/boards-query.spec.ts

Ref #411 
Summary
- Excluded archived notes when counting notes for each board by filtering both deleted and archived notes in board queries, ensuring counts reflect only active notes
- Applied the same archived-note filter to board update responses so that note counts remain consistent after board modifications
- Added an end-to-end test that creates both active and archived notes and verifies the dashboard displays a count of only active notes
E2e

test: verify board query omits archived notes

---

app/dashboard/page.tsx

In relation, to #411 and fixes #426 by aligning the note counter badge to the top

fix: title and note cound card alignment

---

components/sticky-notes-demo.tsx

Cards were compressing/shifting when adding or removing checklist items, causing a poor user experience.
Fix #514
Updated Framer Motion configuration to use `layout="position"` which only animates position changes, preventing unwanted size animations during checklist updates.
- Added `layout="position"` prop to note cards
- Added `layoutId` for stable animation tracking
**Before**
https://github.com/user-attachments/assets/74d1f47d-ac22-443f-a115-3bab25e2c151
**After**
https://github.com/user-attachments/assets/dea14332-ee0d-415c-bfb6-52439400a0bc

fix: Fix card layout compression on checklist item changes

---

app/boards/[id]/page.tsx
tests/e2e/search.spec.ts

Problem: As you can see in the video, initially there are 2 notes. When I search something that isn't present in any note, and click on "Add Note", I cannot see new notes being created which leads to an inconsistent UX 
https://github.com/user-attachments/assets/4622af11-e048-47a0-a4f7-82c8a131d692
Solution: Clear the filters when "Add note" is clicked as it will lead to consistent UX
https://github.com/user-attachments/assets/4e0a5fb8-4eb9-45e7-ba2d-a7d74ecbd37b

fix: search ux when adding a new note

---

tests/e2e/add-task-button.spec.ts
tests/e2e/archive.spec.ts
tests/e2e/auth.spec.ts
tests/e2e/delete-user.spec.ts
tests/e2e/home-page.spec.ts
tests/e2e/notes.spec.ts

This pull request makes E2E tests more reliable and stable, especially when running on multiple workers locally.
**Key improvements:**
* **Unique test data:** The tests now generate unique names, emails, IDs, and tokens for each run to prevent conflicts when multiple workers run tests simultaneously.
* **Better synchronization:** Tests wait for backend API responses before checking results, reducing timing-related failures.
* **Stronger assertions:** Polling is used for database checks to handle delays and ensure accurate results.
* **Reliable interactions:** Actions like clicking or splitting items now wait for backend updates, making tests less flaky.

fix: e2e flaky tests

---

app/boards/[id]/page.tsx

this pr consist of 2 micro changes on the same drop down in boardpage.
before:
https://github.com/user-attachments/assets/aa0d9be0-8c63-4ab7-a22d-aed411ea3c7d
after:
https://github.com/user-attachments/assets/c0480e39-5f66-48d8-acb6-95a4520659cf
---------
before:
https://github.com/user-attachments/assets/4d4b9934-f964-45f3-8afd-7a1edae8616a
after:
https://github.com/user-attachments/assets/cac18784-4dfb-4149-9ef7-d3cfc05c415d

fix: dropdown changes

---

components/note.tsx
tests/e2e/notes.spec.ts

- Fixed an issue where the copy button was visible but non-functional on archived notes
- The copy action button is now properly hidden when a note is archived
- No changes to the copy functionality itself, just the visibility condition
Test result

fix: hide copy button on archived notes

---

components/sticky-notes-demo.tsx

This PR implements the Copy Note functionality in the homepage notes demo.
The "Copy Note" action icon was visible, but clicking it did not perform any action.
Clicking the "Copy Note" icon now successfully copies the note content.
https://github.com/user-attachments/assets/f902e2ed-d9e6-40fa-aee2-f4c39d61e4f2

feat: add copy note functionality to notes demo on homepage

---

app/boards/[id]/page.tsx

- Improved spacing/alignment for:
- Delete Board button
- Buttons previously had inconsistent gaps between icons and text.
Before
After
After view deleting the "delete board" button

fix(ui): improve delete board button spacing issue

---

app/settings/organization/page.tsx

- Improved spacing/alignment for:
- Create Invite Link button
- Buttons previously had inconsistent gaps between icons and text.
Before
After
After view for the moblie

fix(ui): improve "Create Invite Link" button spacing  issue

---

app/auth/error/page.tsx

Before:
https://github.com/user-attachments/assets/c17186d7-077a-49c3-a40c-e73f3169f6ce
After:
https://github.com/user-attachments/assets/e55594c7-e2a8-44b9-8b79-5687fb24b7ac
- Removed dark mode specific styling (`dark:bg-zinc-900 dark:text-zinc-100 dark:border-zinc-700`) from the "Try again" button
- Simplified button styling to use consistent appearance across both light and dark themes
-No AI tools used for this PR and code changes

fix: style of "Try again" button Authentication Error page in dark mode

---

app/page.tsx

Description:
On tablet view, the layout used sm:grid-cols-2 which caused the third card to drop under the first column, creating an awkward visual gap.
This PR enforces md:grid-cols-3 so that three cards align properly at tablet sizes, improving overall UI consistency without making cards too small.
Before:
After:
No AI was used to generate any of this code.

fix: improve tablet responsiveness for card grid

---

app/boards/[id]/page.tsx

Improved UX for Board settings dialog.  
Currently, the dialog can only be closed via the "Cancel" button.  
This change allows the dialog to also close when clicking anywhere outside of it.  
- Added outside click handler for Board settings dialog.
- Preserves existing cancel button functionality.
https://github.com/user-attachments/assets/008b2046-746c-47c0-af81-74cb51d53446
https://github.com/user-attachments/assets/ba132843-6218-468f-8e41-8217da4babbd
- Verified that dialog opens as before.
- Cancel button still closes the dialog.
- Clicking outside now properly closes the dialog.

Fix: allow Board settings dialog to close when clicking outside

---

components/checklist-item.tsx

- Add 'Start typing…' placeholder to new checklist items
- Only shows when isNewItem is true
- Resolves #680
Kindly Review!

feat: add placeholder text for new note checklist items

---

app/auth/error/page.tsx
app/boards/[id]/page.tsx
tests/e2e/board.spec.ts

- Replaced the old board selector dropdown with a shadcn popover for improved UX and cleaner code.
- Added a smooth arrow rotation transition to provide better visual feedback.
- Added e2e tests
https://github.com/user-attachments/assets/4fadc4fc-7fc2-48b8-9cc0-df4d2469c149
Desktop
https://github.com/user-attachments/assets/c1d012d7-478b-46ee-b80d-9456c6d49a83
Mobile
https://github.com/user-attachments/assets/f1d9b08f-e727-4f82-8653-c422efd2baa3
AI was used in figuring out which tailwind classes are unused and can be removed.
Left out the create board dialog migration and its e2e tests to keep this PR focused and easier to review. I’ll open a separate PR for those changes.

refactor(ui): board selector dropdown migration to shadcn

---

tests/e2e/invite-accept.spec.ts

- Added a new **Playwright e2e test suite** for invite acceptance:
- Seeds an **organization invite** before each scenario via a custom `inviteToken` fixture.  
- Ensures every test runs with **fresh invite data**.  
- Covers **valid acceptance**, **decline flow**, and **invalid/expired token** handling.
- Invite acceptance flow is **critical for onboarding collaborators**.  
- Previously untested — risk of regressions in **dashboard redirects, decline status updates, and error handling**.  
- These tests ensure consistent and correct behavior across all invite scenarios.
- Ran the new test suite locally with `npm run test:e2e invite-accept.spec.ts`.  
- All three scenarios passed successfully:  
-  Accepting a valid invite redirects to **Dashboard**.  
-  Declining an invite updates …

test: Add invite acceptance e2e tests

---

tests/e2e/public-board-security.spec.ts

Problem (BEFORE):
- Missing critical security test coverage for public board functionality
- No validation that sensitive organization data isn't leaked via public APIs
- No tests preventing authentication bypass on private boards
- No protection against cross-organization data access
- Security vulnerabilities could go undetected in production
Solution (AFTER):
-  6 comprehensive security test scenarios covering critical attack vectors
- Data leakage prevention - ensures no sensitive org member data exposed
- Authentication bypass prevention - blocks unauthorized private board access
- Cross-organization security - validates proper data isolation
- API security testing - prevents unauthorized note creation attempts
- UI security validation - ensures proper public board restrictions

test: add comprehensive public board security E2E tests

---

app/boards/[id]/page.tsx
components/note.tsx

there were two small truncate issue. so have pushed it in the same pull request.
before:
after:
after:
before:
None

fix: Truncate changes

---

app/boards/[id]/page.tsx

Before:
https://github.com/user-attachments/assets/df72e50f-1633-4dd6-a3f2-d6f2ab763d61
After:
https://github.com/user-attachments/assets/944034f7-ceab-4082-b33c-33dd4582963e
- Updated `variant="outline"` to `variant="default"` for the "Clear all filters" button on Boards page  
- Ensured the button is more clearly visible to the user
- No AI tools used for this PR and code changes

fix: style of 'Clear all filters' button  on boards page

---

components/ui/filter-popover.tsx
tests/e2e/filter-tooltip.spec.ts

ref: #411 
-  Introduced a tooltip that displays "Filters" when hovering over the filter button in the FilterPopover component.
- Before: 
- After: 
- No AI was used to generate any of this code.
- All changes are intuitive, so no additional comments are needed.

feat: add tooltip to filter button in FilterPopover

---

app/boards/[id]/page.tsx

Fix archive state update issue where archived notes don't appear immediately in the archive view.
Part of: #411
When users archive a note and navigate to the archive page, the archived note doesn't appear until the page is manually refreshed. This creates a confusing UX where users think the archive operation failed.
The archive/unarchive operations were delayed by 4 seconds (using `setTimeout`) to allow for undo functionality. When users navigate to the archive page immediately after archiving, the note hasn't been archived in the database yet.
Made archive and unarchive operations execute immediately while preserving the undo functionality through the toast notification.
- Removed 4-second delay from `handleArchiveNote` and `handleUnarchiveNote` functions
- Archive/unarchive API calls …

fix: Remove delay from archive operations

---

components/ui/date-range-picker.tsx

#411
currently when we pick the date start and end. it trigger the api and apply the changes.
but these changes should be only apply when we click on the apply button and not when we pick the date. 
same behavior as the board setting where we only apply the public toggle when we save it.
before:
https://github.com/user-attachments/assets/ee16dc72-ce4b-48f2-988f-49f6aeba43cf
after:
https://github.com/user-attachments/assets/f93534e9-2f85-4ffe-95f9-b918d5149f82
no use of AI in this pr.

fix: make use of apply button in date picker

---

components/note.tsx

Early return `handleToggleChecklistItem` function if `!canEdit`, so checklist items are only clickable for authorized users
Before (The checklist is clickable)
https://github.com/user-attachments/assets/dfe4bd1f-d002-4670-b4cb-60c4d1f0efe0
After (The checklist is not clickable)
https://github.com/user-attachments/assets/523f7bca-6fb3-41f2-be3f-e90d25f6e5d1
No AI tools used

Prevent unauthorized users from toggling checklist items

---

app/settings/organization/page.tsx
tests/e2e/organization-settings.spec.ts

#411 
when we copy, showing a toaster instead of a dialog make much more sense. dialog is great when we want confirmation but in the case of copy we are not doing that. so keeping a toaster can enhance the UX by reducing the unnecessary extra steps in between.
> same as we did for delete of card  #332
https://github.com/user-attachments/assets/48ee1bb8-3b79-40ef-bad4-bba9bfd7e489
https://github.com/user-attachments/assets/4d6f9658-ab57-4453-b9ff-82d48b2386bf
took help of cursor (claude 4)  to validate e2e test. 
test is self reviewed.

fix: toaster instead of dialog when we copy link

---

.env.example

pr #775 have delete the env examples. I believe it is an accidental merge

fix: bring back .env.example
