antiwork/gumboard

.github/workflows/ci.yml
.gitignore
jest.config.js
package-lock.json
package.json
playwright.config.ts
tests/e2e/auth.spec.ts
tests/e2e/board.spec.ts
tests/e2e/notes.spec.ts
tests/e2e/todo-conversion.spec.ts
tests/fixtures/test-helpers.ts

Fixes #2 
- Add 4 test scenarios: auth, board creation, notes with newlines, todo conversion
- Implement auth mocking for faster test execution
- Configure Jest to exclude e2e tests
- Add Playwright configuration and test helpers
- Update .gitignore to exclude test output directories

[WIP] feat(tests-e2e): Add basic Playwright e2e tests

---

app/boards/[id]/page.tsx

- Updated the onClick handlers for author and sort dropdowns to use if statements for better readability and maintainability.
- Ensured that the sort dropdown closes when the author dropdown is opened and vice versa.

Refactor dropdown toggle logic in BoardPage component

---

README.md

Add: Vercel Deploy Button

---

app/boards/[id]/page.tsx

Revert "feat: effect for polling every 5 seconds"

---

app/boards/[id]/page.tsx

This PR significantly enhances the user experience by introducing optimistic updates across user interactions in the boards/[id] page.
Before - 
https://github.com/user-attachments/assets/d9525824-0a78-4b58-bd46-d8bf65690a62
After - 
https://github.com/user-attachments/assets/bed4f170-0625-49d0-9e23-75c71d6a4664
Functions Enhanced are - 
-  handleToggleChecklistItem()
- handleToggleDone()
- handleUpdateNote()
- handleAddChecklistItem()
- handleDeleteChecklistItem()
This removes UI delays.

Optimistic UX update

---

README.md
app/auth/signin/page.tsx
auth.ts
env.example
tests/e2e/auth.spec.ts
tests/e2e/github-auth.spec.ts

[Screen-Recording(2).webm](https://github.com/user-attachments/assets/4bba87ca-bd25-4404-8371-613f2974f40e)
Fixes #117

Add GitHub auth

---

components/ui/switch.tsx

Fixes https://github.com/antiwork/gumboard/issues/186

fix: public toggle styling issue

---

app/boards/[id]/page.tsx
components/ui/filter-popover.tsx

Fixes https://github.com/antiwork/gumboard/issues/196
https://github.com/user-attachments/assets/1c37405d-583c-4ed0-90d5-e7fa387bdcd4
https://github.com/user-attachments/assets/44cb3bef-0005-441a-8939-3436775a584c

fix: Make Board page header fully responsive on smaller screens

---

app/boards/[id]/page.tsx
components/note.tsx
tests/e2e/add-task-button.spec.ts
tests/e2e/archive.spec.ts
tests/e2e/notes.spec.ts

Fixes #221
https://github.com/user-attachments/assets/9dd3f711-43be-41e9-89ca-5a8c1202660e
All the note actions are now working
https://github.com/user-attachments/assets/6e4ff1f4-8f60-4afd-9324-53d5c8b743db
Fixed mock data to make tests pass again

fix: note actions on `all-notes` board

---

app/boards/[id]/page.tsx
tests/e2e/board-settings.spec.ts

Fixes failing tests in https://github.com/antiwork/gumboard/pull/184

fix: tests in #184

---

components/theme-provider.tsx

context: this pr fixes light mode problems locally and i'd suggest scrolling down to see the screen recording (added for demonstration & reproduction reasons)

Fix local theme bug

---

app/boards/[id]/page.tsx
app/dashboard/page.tsx
app/settings/layout.tsx
components/profile-dropdown.tsx

Replaced all instances of the old dropdown with the new dropdown button.
Created a reusable `profile-dropdown.tsx` component to improve readability, maintainability, and consistency across pages.
cc @ershad @slavingia

refactor(ui): migrate new user dropdown to all pages

---

prisma/schema.prisma

It's a feature that's been in preview for over a year and it's quite good;  it's a client-level feature that optimizes queries significantly using JOINs (thus reducing round-trips).
https://www.prisma.io/docs/orm/prisma-client/queries/relation-queries
Seed data:
```
Organizations: 1
Users: 5
Boards: 10
Notes: 5,000 total
Notes per board: 500
Additional details:
- 80% active notes (4,000)
- 20% archived notes (1,000)
```
<details>
<summary>Non-related joins benchmark</summary>
```bash
Running benchmarks...
Running: GET /api/boards
Duration: 4.27ms (avg of 10 runs)
Queries per run: 3
Total queries: 30
Running: GET /api/boards/[id]/notes
Duration: 8.97ms (avg of 10 runs)
Queries per run: 4
Total queries: 40
Running: GET /api/boards/all-notes/notes
Duration: 79.74ms (avg of 10 runs)
Queries …
```

feat: enable relation joins in Prisma

---

package-lock.json

Some weird npm thing, few dependencies were removed causing tests and build to not run
Went through https://github.com/parcel-bundler/lightningcss/issues/567#issuecomment-2579204281 and applied the steps. As discussed in these threads, locally everything seems to work 
Linking relevant threads
1. https://github.com/parcel-bundler/lightningcss/issues/567
2. https://github.com/npm/cli/issues/4828

Github Actions Failing 

---

components/note.tsx
tests/e2e/add-task-button.spec.ts
tests/e2e/archive.spec.ts
tests/e2e/home-page.spec.ts
tests/e2e/notes.spec.ts

This should get all E2E tests working so PR #312 moves forward

fix: note-height-calculation e2e tests

---

app/auth/signin/page.tsx

fixed broken styles on auth/signin page
before:
https://github.com/user-attachments/assets/6f7fbdb4-4e44-4c91-bac8-28a91412d326
https://github.com/user-attachments/assets/ecd9bc29-b3f1-4938-9aaa-81cfd3e20d61
after:
https://github.com/user-attachments/assets/3f3f7540-220b-4925-bc54-c6c64a343dba
https://github.com/user-attachments/assets/b35479b7-7343-49ce-b077-121c1bc11a77

fix: improved styles on auth/signin page

---

app/api/boards/[id]/notes/route.ts
app/api/boards/all-notes/notes/route.ts
app/api/boards/archive/notes/route.ts
components/checklist-item.tsx
components/note.tsx

- Fixed dark mode styles in checklist component 
- included `user image` in notes apis to show in every note @slavingia do you think we should keep this change or drop it?
Before
https://github.com/user-attachments/assets/c5c0c749-aa0f-4c52-a7cd-70ce3d937ae3
After
https://github.com/user-attachments/assets/bf0e4a1a-0675-4b41-920d-9c767003cd85

fix: dark mode styles in notes checklist

---

app/boards/[id]/page.tsx

Fixed multiple UI issues in the board create/settings dialog (colors, borders, alignment, responsiveness), improving overall smoothness and addressing #411.
Before
https://github.com/user-attachments/assets/6171d712-09b0-443e-a9a2-786d81b6cad3
After
https://github.com/user-attachments/assets/e644ffd2-be63-4cc9-aabb-b7b236eabb0f

fix: board create/settings ui

---

app/dashboard/page.tsx
app/public/boards/[id]/page.tsx

Fixes #411
@slavingia
What was broken:
- **Dashboard fails silently** - when it breaks, you get no feedback, just sit there wondering what's wrong
- **Public boards get stuck loading forever** - super embarrassing when sharing with clients
What I fixed:
- **Dashboard now shows error dialogs** instead of silent failures
- **Public boards fail gracefullywith proper not-found pages instead of infinite loading
- `app/dashboard/page.tsx` - added error dialog
- `app/public/boards/[id]/page.tsx` - proper error fallback  
all tests pass 
Happy to make any changes if needed!

Fix #411: Improve product quality with better error handling

---

lib/slack.ts

tech debt: removed unnecessary console logs

---

app/invite/accept/page.tsx

Invite-Accept UI Improve

---

app/public/boards/[id]/page.tsx
components/note.tsx
components/ui/draggable.tsx

This PR fixes hydration mismatch issues in both the Note and Draggable components that were causing React warnings in the console.
1. **Note Component**:
- Removed `resolvedTheme` dependency
- Moved background color logic to parent components
- Simplified component styling
2. **Draggable Component**:
- Fixed dynamic `aria-describedby` IDs
- Ensured consistent ID generation between server and client
- Improved accessibility with stable IDs
These hydration fixes eliminate React warnings by ensuring server and client rendering match. We moved theme logic to parent components and removed dynamic IDs that caused mismatches. This makes the app more stable and maintainable without changing functionality.

fix: resolve hydration mismatches in Note and Draggable components

---

app/settings/organization/page.tsx
app/settings/page.tsx
components/ui/number-field.tsx
tests/e2e/notes.spec.ts

- Replaced the native HTML <input type="date" /> with a consistent Popover + Calendar date picker.
- Keeps the same functionality:
-  Stores date as yyyy-MM-dd in state (unchanged).
- Displayed to users as dd-MM-yyyy.
- Non-admin users still cannot change the expiry date.
- Improves UX with better dark mode support and unified styling.
- No backend or API changes.
- Behavior is identical to the previous implementation, only the UI is upgraded.
- E2E tests were updated to interact with the new calendar UI instead of the native date input. This removes flakiness around disabled cells and ensures tests click only visible, enabled date buttons.
https://github.com/user-attachments/assets/709ebb41-4686-4d5d-ac61-8d4c1d2cce0c
https://github.com/user-attachments/assets/ab827582-c48d-436f-a2f4-dfee …

feat: enhance invites UI/UX with calendar picker, cancel feedback, and number input

---

app/settings/organization/page.tsx
tests/e2e/organization-settings.spec.ts

ref: #411 
- Resolved issue where saving organization name also triggered the Slack webhook save button state
- Added separate state management for organization name and Slack webhook save operations
- Included E2E test to verify independent button behavior
- Before: 
https://github.com/user-attachments/assets/3019567b-deb2-4a45-8388-0f1361a97fa0
- After: 
https://github.com/user-attachments/assets/8d2e446b-9053-4a52-ac8a-764889f30340
- I have used Cursor to generate tests, and the implementation was done by myself.
- All changes are intuitive, so no additional comments are needed.

fix: ensure independent save button states for organization settings
